apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Project-PVC
  namespace: abu-nemr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-ebs