apiVersion: v1
kind: Service
metadata:
  name: SVC-APP
  namespace: abu-nemr
spec:
  selector:
    app: Project-App
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP