---
# tasks file for roles/prerequisite
    - name: Update and upgrade apt
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install prerequisites
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg2
          - software-properties-common
          - unzip
          - openjdk-17-jdk
          - openjdk-17-jre
        state: present
        update_cache: yes
